DROP TABLE IF EXISTS LOANS;
DROP TABLE IF EXISTS BOOKS;
DROP TABLE IF EXISTS DV_DS;
DROP TABLE IF EXISTS AUDIOCDS;
DROP TABLE IF EXISTS LIBRARY_ITEM;
DROP TABLE IF EXISTS PATRON;


CREATE TABLE PATRON(

	ID BIGINT NOT NULL PRIMARY KEY auto_increment,
    IN_USE BIT NOT NULL DEFAULT 1,
    NUM_OF_ITEMS_RENTED INT NOT NULL DEFAULT 0,
    PATRON_FIRST_NAME VARCHAR(255) NOT NULL,
    PATRON_LAST_NAME VARCHAR(255) NOT NULL,
    PATRON_STATUS INT NOT NULL DEFAULT 0


);

CREATE TABLE LIBRARY_ITEM(

ITEMID BIGINT NOT NULL PRIMARY KEY auto_increment,
COST DOUBLE NOT NULL,
ITEM_TYPE VARCHAR(31) NOT NULL,
STATUS INT NOT NULL DEFAULT 0,
LOAN_DAYS INT NOT NULL,
RELEASE_DATE DATETIME NOT NULL,
TITLE VARCHAR(255) NOT NULL


);


CREATE TABLE AUDIOCDS(

ITEMID BIGINT PRIMARY KEY NOT NULL,
ARTIST VARCHAR(255) NOT NULL,
GENRE VARCHAR(255) NOT NULL,
NUMBER_OF_TRACKS INT NOT NULL,


FOREIGN KEY (ITEMID) REFERENCES LIBRARY_ITEM(ITEMID)






);



CREATE TABLE BOOKS(

ITEMID BIGINT PRIMARY KEY NOT NULL,
AUTHOR_FIRST_NAME VARCHAR(255) NOT NULL,
AUTHOR_LAST_NAME VARCHAR(255) NOT NULL,

FOREIGN KEY (ITEMID) REFERENCES LIBRARY_ITEM(ITEMID)




);



CREATE TABLE DV_DS(

ITEMID BIGINT PRIMARY KEY NOT NULL,
CATEGORY VARCHAR(255) NOT NULL,
RUN_TIME INT NOT NULL,
STUDIO_NAME VARCHAR(255) NOT NULL,



FOREIGN KEY (ITEMID) REFERENCES LIBRARY_ITEM(ITEMID)




);


CREATE TABLE LOANS(

LOANID BIGINT PRIMARY KEY NOT NULL auto_increment,
LOAN_DUE_DATE DATETIME NOT NULL,
STATUS INT NOT NULL DEFAULT 0,
NUMBER_OF_RECHECKS TINYINT NOT NULL DEFAULT 1,
LIBRARY_ITEM_ITEMID BIGINT NOT NULL,
PATRON_ID BIGINT NOT NULL,


FOREIGN KEY ( LIBRARY_ITEM_ITEMID) REFERENCES LIBRARY_ITEM(ITEMID),
FOREIGN KEY (PATRON_ID) REFERENCES PATRON(ID)





);







